export const CLIENTINFO_REQUEST = 'CLIENTINFO_REQUEST';
export const CLIENTINFO_SUCCESS = 'CLIENTINFO_SUCCESS';
export const CLIENTINFO_ERROR = 'CLIENTINFO_ERROR';

export const PROFESSIONALINFO_REQUEST = 'PROFESSIONALINFO_REQUEST';
export const PROFESSIONALINFO_SUCCESS = 'PROFESSIONALINFO_SUCCESS';
export const PROFESSIONALINFO_ERROR = 'PROFESSIONALINFO_ERROR';