export const CLIENTS_REQUEST = 'CLIENTS_REQUEST';
export const CLIENTS_SUCCESS = 'CLIENTS_SUCCESS';
export const CLIENTS_ERROR = 'CLIENTS_ERROR';

export const COACHES_REQUEST = 'COACHES_REQUEST';
export const COACHES_SUCCESS = 'COACHES_SUCCESS';
export const COACHES_ERROR = 'COACHES_ERROR';