export const CLIENTS_REQUEST = 'CLIENTS_REQUEST';
export const CLIENTS_SUCCESS = 'CLIENTS_SUCCESS';
export const CLIENTS_ERROR = 'CLIENTS_ERROR';

export const PROFESSIONALS_REQUEST = 'PROFESSIONALS_REQUEST';
export const PROFESSIONALS_SUCCESS = 'PROFESSIONALS_SUCCESS';
export const PROFESSIONALS_ERROR = 'PROFESSIONALS_ERROR';