export const CLIENT_PROFILE_REQUEST = 'CLIENT_PROFILE_REQUEST';
export const CLIENT_PROFILE_SUCCESS = 'CLIENT_PROFILE_SUCCESS';
export const CLIENT_PROFILE_ERROR = 'CLIENT_PROFILE_ERROR';

export const TRAINER_PROFILE_REQUEST = 'TRAINER_PROFILE_REQUEST';
export const TRAINER_PROFILE_SUCCESS = 'TRAINER_PROFILE_SUCCESS';
export const TRAINER_PROFILE_ERROR = 'TRAINER_PROFILE_ERROR';
