export const CLIENT_PROFILE_REQUEST = 'CLIENT_PROFILE_REQUEST';
export const CLIENT_PROFILE_SUCCESS = 'CLIENT_PROFILE_SUCCESS';
export const CLIENT_PROFILE_ERROR = 'CLIENT_PROFILE_ERROR';

export const PROFESSIONAL_PROFILE_REQUEST = 'PROFESSIONAL_PROFILE_REQUEST';
export const PROFESSIONAL_PROFILE_SUCCESS = 'PROFESSIONAL_PROFILE_SUCCESS';
export const PROFESSIONAL_PROFILE_ERROR = 'PROFESSIONAL_PROFILE_ERROR';
