export const PROPOSE_TERMS_REQUEST = 'PROPOSE_TERMS_REQUEST';
export const PROPOSE_TERMS_SUCCESS = 'PROPOSE_TERMS_SUCCESS';
export const PROPOSE_TERMS_ERROR = 'PROPOSE_TERMS_ERROR';

export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';