export const HIRE_SUCCESS = 'HIRE_SUCCESS';
export const HIRE_ERROR = 'HIRE_ERROR';

export const CONTRACT_CHANGEFORM = 'CONTRACT_CHANGEFORM';
export const PAYMENT_CHANGEFORM = 'PAYMENT_CHANGEFORM';
export const PAYMENT_LOADING = 'PAYMENT_LOADING';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_ERROR = 'GET_CARDS_ERROR';