export const HIRE_SUCCESS = 'HIRE_SUCCESS';
export const HIRE_ERROR = 'HIRE_ERROR';
export const HIRE_RESET = 'HIRE_RESET';

export const CONTRACT_REQUEST = 'CONTRACT_REQUEST';
export const CONTRACT_CHANGEFORM = 'CONTRACT_CHANGEFORM';
export const CONTRACT_CHOOSE_SCREEN = 'CONTRACT_CHOOSE_SCREEN';
export const PAYMENT_CHANGEFORM = 'PAYMENT_CHANGEFORM';
export const PAYMENT_LOADING = 'PAYMENT_LOADING';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';