export const FORM_NAMES = {
    FIRST_FORM: 'FIRST_FORM',
    SECOND_FORM: 'SECOND_FORM',
    SUMMARY_FORM: 'SUMMARY_FORM',
    PAYMENT_FORM: 'PAYMENT_FORM',
};

export const SUMMARY_FORM_TYPES = {
    CREATE: 'CREATE',
    ACCEPT: 'ACCEPT',
    VIEW: 'VIEW',
};