export const EXPLORE_GET_ERROR = 'EXPLORE_GET_ERROR';
export const EXPLORE_GET_REQUEST = 'EXPLORE_GET_REQUEST';
export const EXPLORE_GET_SUCCESS = 'EXPLORE_GET_SUCCESS';
export const EXPLORE_SET_FILTERS = 'EXPLORE_SET_FILTERS';
