export const EXPLORE_GET_CLIENTS = 'EXPLORE_GET_CLIENTS';
export const EXPLORE_GET_CLIENTS_SUCCESS = 'EXPLORE_GET_CLIENTS_SUCCESS';
export const EXPLORE_GET_CLIENTS_ERROR = 'EXPLORE_GET_CLIENTS_ERROR';

export const EXPLORE_GET_PROFESSIONALS = 'EXPLORE_GET_PROFESSIONALS';
export const EXPLORE_GET_PROFESSIONALS_SUCCESS = 'EXPLORE_GET_PROFESSIONALS_SUCCESS';
export const EXPLORE_GET_PROFESSIONALS_ERROR = 'EXPLORE_GET_PROFESSIONALS_ERROR';