export const INBOX_REQUEST = 'INBOX_REQUEST';
export const INBOX_SUCCESS = 'INBOX_SUCCESS';
export const INBOX_ERROR = 'INBOX_ERROR';
export const INBOX_ADD = 'INBOX_ADD';

export const INBOX_ACTIVATE_CHAT_REQUEST = 'INBOX_REQUEST_ACTIVATE_CHAT';
export const INBOX_ACTIVATE_CHAT_SUCCESS = 'INBOX_ACTIVATE_CHAT_SUCCESS';
export const INBOX_ACTIVATE_CHAT_ERROR = 'INBOX_ACTIVATE_CHAT_ERROR';
export const INBOX_DEACTIVATE_CHAT = 'INBOX_DEACTIVATE_CHAT';
export const INBOX_UPDATE_WITH_NEW_MESSAGE = 'INBOX_UPDATE_WITH_NEW_MESSAGE';

export const MESSAGES_REQUEST = 'MESSAGES_REQUEST';
export const MESSAGES_SUCCESS = 'MESSAGES_SUCCESS';
export const MESSAGES_ERROR = 'MESSAGES_ERROR';
export const MESSAGES_ADD_NEW = 'MESSAGES_ADD_NEW';
export const MESSAGES_UNREAD_EVENT = 'MESSAGES_UNREAD_EVENT';